# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-10-11 07:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20191008_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gallery.Location'),
        ),
    ]
